-- Acme editor color scheme
local lexers = vis.lexers

lexers.STYLE_DEFAULT = ''
lexers.STYLE_NOTHING = ''
lexers.STYLE_CLASS = ''
lexers.STYLE_COMMENT = ''
lexers.STYLE_CONSTANT = ''
lexers.STYLE_DEFINITION = ''
lexers.STYLE_ERROR = ''
lexers.STYLE_FUNCTION = ''
lexers.STYLE_KEYWORD = ''
lexers.STYLE_LABEL = ''
lexers.STYLE_NUMBER = ''
lexers.STYLE_OPERATOR = ''
lexers.STYLE_REGEX = ''
lexers.STYLE_STRING = ''
lexers.STYLE_PREPROCESSOR = ''
lexers.STYLE_TAG = ''
lexers.STYLE_TYPE = ''
lexers.STYLE_VARIABLE = ''
lexers.STYLE_WHITESPACE = ''
lexers.STYLE_EMBEDDED = ''
lexers.STYLE_IDENTIFIER = ''

lexers.STYLE_LINENUMBER = ''
lexers.STYLE_LINENUMBER_CURSOR = ''
lexers.STYLE_CURSOR = 'reverse'
lexers.STYLE_CURSOR_PRIMARY = 'back:yellow,fore:black'
lexers.STYLE_CURSOR_LINE = ''
lexers.STYLE_COLOR_COLUMN = ''
lexers.STYLE_SELECTION = 'back:#DDDDDD'
lexers.STYLE_STATUS = 'fore:#999999'
lexers.STYLE_STATUS_FOCUSED = 'fore:default'
lexers.STYLE_SEPARATOR = ''
lexers.STYLE_INFO = ''
lexers.STYLE_EOF = 'fore:#CCCCCC'

